name: SonarCloud
on:
  push:
    branches:
      - main
jobs:
  code_analysis:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: '17'
    - name: Analyze with SonarCloud
      run: | 
        chmod +x ./mvnw
        ./mvnw -B verify sonar:sonar -Dsonar.projectKey=ribeirofeu_techfood-ms-production -Dsonar.organization=ribeirofeu -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=$SONAR_TOKEN
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
